### ISSUE TITLE
Update repository to the latest SvelteKit version

### ISSUE THREAD

**Issue by azmith10k** [V-Py/svelte-kanban#45]
Hey, just stumbled on to your library while I was trying to implement my own hobbyist kanban-style Todo app using SvelteKit. One glance through it and it is amazing!

I cloned the repo to analyze the code and I couldn't execute `npm run dev` because the repo still follows an older version of SvelteKit. They have made quite a few changes to routing and the build scripts use `vite` instead of `svelte-kit` for example. Is there any chance that you would update this project to the latest SvelteKit version?

**Comment by V-Py** [comment]
Hey and thank you for your kind words!
You're totally right, I'll do the upgrade asap, hopefully tomorrow, should be quick
